# Generated by Django 2.1.5 on 2021-08-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('field_name', models.EmailField(max_length=355)),
                ('body', models.TextField()),
            ],
        ),
    ]
