# Generated by Django 2.1.5 on 2021-08-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_card'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='News',
        ),
    ]
