# Generated by Django 2.1.5 on 2021-08-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210808_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='field_name',
            field=models.EmailField(max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='field_name',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
