# Generated by Django 2.1.5 on 2021-08-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210808_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='field_name',
            new_name='email',
        ),
    ]
