# Generated by Django 2.1.5 on 2021-08-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210808_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('title', models.CharField(max_length=255, null=True)),
                ('text', models.TextField(max_length=255, null=True)),
                ('body', models.TextField(null=True)),
            ],
        ),
    ]
