# Generated by Django 2.1.5 on 2021-08-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='body1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image1',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='news',
            name='image2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='news',
            name='title1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
