# Generated by Django 2.1.5 on 2021-08-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_top_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top',
            name='image',
        ),
    ]
