# Generated by Django 2.1.5 on 2021-08-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_top_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='top',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
